# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: service.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rservice.proto\"\x10\n\x02Id\x12\n\n\x02id\x18\x01 \x01(\r\")\n\x04Stat\x12\x10\n\x08\x63omments\x18\x01 \x01(\r\x12\x0f\n\x07symbols\x18\x02 \x01(\r2%\n\x0bStatService\x12\x16\n\x08\x43\x61lcStat\x12\x03.Id\x1a\x05.Statb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'service_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _ID._serialized_start=17
  _ID._serialized_end=33
  _STAT._serialized_start=35
  _STAT._serialized_end=76
  _STATSERVICE._serialized_start=78
  _STATSERVICE._serialized_end=115
# @@protoc_insertion_point(module_scope)
