# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import service_pb2 as service__pb2


class StatServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CalcStat = channel.unary_unary(
                '/StatService/CalcStat',
                request_serializer=service__pb2.Id.SerializeToString,
                response_deserializer=service__pb2.Stat.FromString,
                )


class StatServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CalcStat(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_StatServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CalcStat': grpc.unary_unary_rpc_method_handler(
                    servicer.CalcStat,
                    request_deserializer=service__pb2.Id.FromString,
                    response_serializer=service__pb2.Stat.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'StatService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class StatService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CalcStat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/StatService/CalcStat',
            service__pb2.Id.SerializeToString,
            service__pb2.Stat.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
